version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  # Serviço Python - ETL
  etl:
    build: .
    container_name: python-etl
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase 
    command: /app/venv/bin/python backend/etl/run_etl.py 

volumes:
  mongo-data:
